= Satellite: A Deep Dive into Troubleshooting

In this hands-on troubleshooting lab we will troubleshoot common issues that are encountered in Red Hat Satellite deployments, identify and solve content and synchronization issues, fix client connectivity issues, and show how a Standard Operating Environment enhances the customer experience.

This lab provides real-world scenarios to help you diagnose and resolve content synchronization, execution and client connectivity issues in Red Hat Satellite.

.Key skills covered:

****
Include:
    - Validate and rectify issues with repositories and synchronization of Satellite and Capsules
    - Tune Satellite server to resolve performance issues
    - Troubleshoot client connectivity and registration
    - Investigate Remote Execution failures
****


=== Lab Access

The terminal window to your right is *already* logged into the lab environment as the `{root}` user via `ssh`. 
All steps of this lab on the Satellite server, Capsule server and clients are to be completed as the `{root}` user.
