= Satellite: A Deep Dive into Troubleshooting

This hands-on lab provides real-world scenarios to help you diagnose and solve common issues in Red Hat Satellite deployments.
Topics include troubleshooting content and synchronization issues, client connectivity, and demonstrating how a Standard Operating Environment (SOE) enhances the customer experience.

Scenarios covered in this lab:
   
* Validating and rectifying content synchronization issues affecting Satellite and Capsules
* Tuning Satellite server to resolve performance issues
* Troubleshooting client connectivity and registration
* Investigating Remote Execution failures


=== Lab Access

The terminal window to your right is *already* logged into the lab environment via SSH as the `{root}` user. 
All steps of this lab on the Satellite server, Capsule server and clients are to be completed with elevated privileges.

*Note:* When copying commands for each module, avoid middle click paste (adds additional characters to the commands). 

== Satellite server web console access:
  * Web URL: `{workshop_satellite_url}`
  * User: `{workshop_satellite_user_name}`
  * Password: `{workshop_satellite_user_password}`

== Access other instances from Bastion

* Log in to the satellite server from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh -i ~/.ssh/{guid}key.pem ec2-user@satellite
----

* Log in to the capsule server from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh -i ~/.ssh/{guid}key.pem ec2-user@capsule
----

* Log in to the additional nodes from bastion:

[subs=attributes+]
----
[lab-user@bastion ~]$ ssh -i ~/.ssh/{guid}key.pem ec2-user@node1
[lab-user@bastion ~]$ ssh -i ~/.ssh/{guid}key.pem ec2-user@node2
[lab-user@bastion ~]$ ssh -i ~/.ssh/{guid}key.pem ec2-user@node3
----
