= Module 2 - Troubleshooting Client Connectivity

In this module, we will explore scenarios affecting connectivity between Satellite server, Satellite capsule, client and remote execution. +

== Environment
* `bastion`   - RHEL 9 jump host
* `satellite` - Red Hat Satellite Server 6.15
* `capsule`   - Red Hat Satellite Capsule 6.15
* `node2`     - RHEL 9 client

{empty} +

[#scenario 1]
== Scenario 1: Troubleshoot client registration errors

Connectivity issues prevent clients from accessing Red Hat content including security fixes which is a compliance risk. +
In addition, the client does not benefit from the intelligence provided by Red Hat Insights. +

The objective of this scenario is to investigate and resolve issues which prevents a client from registering with or accessing content from Red Hat Satellite. +

Access the bastion node through the terminal on the right, or using SSH and switch to root user.

[source,sh,role=execute,subs="attributes"]
----
sudo -i
----

Run the following command to introduce the registration failure.

[source,sh,role=execute,subs="attributes"]
----
lab client_registration
----


=== Task: Client registration

* Login to `node2`

[source,sh,role=execute,subs="attributes"]
----
ssh root@{node2_public_hostname}
----

* Display registration status. The command is expected to return a failure output.

[source,sh,role=execute,subs="attributes"]
----
subscription-manager status
----

* Stop the stuck command by pressing Ctrl + C.

* Examine the subscription management log

[source,sh,role=execute,subs="attributes"]
----
tail /var/log/rhsm/rhsm.log
----

* Inspect the rhsm.conf file

[source,sh,role=execute,subs="attributes"]
----
cat /etc/rhsm/rhsm.conf
----

* We can see that custom proxy settings are in use.

[source,sh,role=execute,subs="attributes"]
----
grep ^proxy /etc/rhsm/rhsm.conf
----

Output
----
   proxy_hostname = proxy.example.com
   proxy_scheme = http
   proxy_port = 8080
----

* Remove the custom proxy settings

[source,sh,role=execute,subs="attributes"]
----
subscription-manager config --server.proxy_hostname "" --server.proxy_port "" --server.proxy_user "" --server.proxy_password ""
----

* Edit the `rhsm.conf` file to replace the false hostname with the correct FQDN of the Satellite server.

[source,sh,role=execute,subs="attributes"]
----
sed -i 's/hostname =.*/hostname = {satellite_public_hostname}/' /etc/rhsm/rhsm.conf
----

----
sed -i 's/baseurl =.*/baseurl = https://{satellite_public_hostname}/pulp/content' /etc/rhsm/rhsm.conf
----

* On `satellite`, generate a Global Registration command (insecure option used to disable SSL validation)

[source,sh,role=execute,subs="attributes"]
----
hammer host-registration generate-command \
--activation-keys "My_Activation_Key" \
--insecure true
----

* Paste the registration command on `node2`. Note: Do not copy this command, use the command generated by Satellite
The registration is expected to fail with error.

----
set -o pipefail && curl -sS --insecure 'https://{satellite_public_hostname}/register?activation_keys=GENERAL&force=1&location_id=2&organization_id=1&setup_insights=0&setup_remote_execution=1&setup_remote_execution_pull=0' -H 'Authorization: Bearer TOKEN' | bash
----

Output:
----
  # Running registration
  #
  This system is currently not registered.
  All local data removed
  subscription-manager is already installed!
  Proxy error: unable to connect to proxy.example.com:8080: Name or service not known (error code -2)
----

* Run the registration command. This time the registration should be successful.

----
set -o pipefail && curl -sS --insecure 'https://{satellite_public_hostname}/register?activation_keys=GENERAL&force=1&location_id=2&organization_id=1&setup_insights=0&setup_remote_execution=1&setup_remote_execution_pull=0' -H 'Authorization: Bearer TOKEN' | bash
----

Output:
----
# Running registration
#
subscription-manager is already installed!
The system has been registered with ID: 213874ca-6ccf-4e5b-a3f1-147d8f1c521b
The registered system name is: {node2_public_hostname}
----

* Display registration status. The command is expected to run successfully.

[source,sh,role=execute,subs="attributes"]
----
subscription-manager status
----

Output:
----
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Disabled
Content Access Mode is set to Simple Content Access. This host has access to content, regardless of subscription status.

System Purpose Status: Disabled
----

{empty} +

[#scenario 2]
== Scenario 2: Troubleshoot Remote Execution

Remote execution enables administrators to run tasks simultaneously on multiple hosts using Ansible or shell scripts. +
Failure to execute causes significant disruption, especially in large Red Hat Satellite deployments. +

The objective of this scenario is to investigate and remediate issues preventing remote execution of jobs. +

Access the bastion node through the terminal on the right, or using SSH and switch to root user.

[source,sh,role=execute,subs="attributes"]
----
sudo -i
----

Run the following command to introduce remote execution failure.

[source,sh,role=execute,subs="attributes"]
----
lab break client_execution
----


=== Task: Remote execution

* On the Satellite server UI, create a Remote execution job to execute on `node2`. +
* Navigate to `Monitor` -> `Jobs` -> `Run job`.

    Job Category: Commands
    Job template: Run Command - Script Default

* Click `Next`

    Target hosts and input: node2
    command: date

* Click `Run on selected hosts`

* Examine the job output. The job fails because the Remote Execution SSH public key used by the Satellite server does not exist on `node2`.

* On `satellite`, copy the SSH public key to `node2`.

[source,sh,role=execute,subs="attributes"]
----
scp /var/lib/foreman-proxy/ssh/id_rsa_foreman_proxy.pub node2:~/.ssh/authorized_keys 
----

* Re-run the Remote Execution job on `node2`. The job should run successfully.

{empty} +

[#scenario 3]
== Scenario 3: Troubleshoot Capsule Connectivity

Capsules servers mirror content from Satellite server, bringing content and Satellite services closer to clients in distinct geographical or logical locations. +
Connectivity issues between Satellite and Capsules can result in corrupt or inconsistent data being served to clients. +

The objective of this scenario is to investigate and remediate issues affecting connectivity between clients and Red Hat Satellite Capsule. +

Access the bastion node through the terminal on the right, or using SSH and switch to root user.

[source,sh,role=execute,subs="attributes"]
----
sudo -i
----

Run the following command to introduce Capsule connectivity failure.

[source,sh,role=execute,subs="attributes"]
----
lab break client_capsule
----


=== Task: Capsule connectivity

* On `node2`, (already registered to Capsule), display the registration status.

[source,sh,role=execute,subs="attributes"]
----
subscription-manager status
----

* Install a package. Note: Package installation is expected to fail.

[source,sh,role=execute,subs="attributes"]
----
dnf install bash-completion
----

* On `capsule`, test network ports.

[source,sh,role=execute,subs="attributes"]
----
nc -v {satellite_public_hostname} 443
----

[source,sh,role=execute,subs="attributes"]
----
nc -v {satellite_public_hostname} 5646
----

[source,sh,role=execute,subs="attributes"]
----
nc -v {satellite_public_hostname} 5647
----

* On `satellite`, check the responsiveness of core services.

[source,sh,role=execute,subs="attributes"]
----
hammer ping
----

* On the `satellite`, check certificate exchange with Capsule. Expected to fail.

[source,sh,role=execute,subs="attributes"]
----
curl -v https://{capsule_public_hostname}/pulp/api/v2/status/ | python -m json.tool  
----

[source,sh,role=execute,subs="attributes"]
----
curl --cert /etc/foreman/client_cert.pem --key /etc/foreman/client_key.pem --cacert /etc/foreman/proxy_ca.pem https://{capsule_public_hostname}:9090/features | python3 -m json.tool
----

Cause: A firewall or proxy, which is located between the Satellite and Capsule servers, is making a certificate modification during the certification validation process. It needs to be checked and corrected.
