= Module 3 - Trouble Shooting Perfomance and Implementing a Standard Operating Environment

== Introduction

Administrators will often need to maintain a Satellite Server for a long period of time, as the Satellite Server becomes an integral part of their organization's infrastructure.

The primary goal of this scenario is to investigate performance and maintainance configurations for the Satellite Server, correct misconfigurations, and automate maintainance cycles as part of the Standard Operating Environment Method of deploying Red Hat Satellite.

[#bfxactivity]
== Executing the Lab Script


In this exercise setup, you first need to access the bastion through `{bastion_public_hostname}` to gain entry into the lab environment. From the terminal on right side, access SSH the node bastion.


[source,sh,role=execute,subs="attributes"]
----
ssh {user}@{bastion_public_hostname} -p {bastion_ssh_port}
----

run the command to break the lab

[source,sh,role=execute,subs="attributes"]
----
lab break module3
----

== Satellite Performance Tuning

=== Scenario

Other teams in your organization have notified you that the Satellite Server does not seem to be performing well. The Server has had additional memory and CPU added to the virtual machine as your organization has provisioned several thousand hosts and performance managing the hosts is still slow. You have been asked to implement tuning based on the new size of the Satellite Server.

Inspect the new number of CPU cores
----
nproc
----

Inspect the new amount of memory
----
free -h 
----

Inspect the current tuning
----
grep tuning /etc/foreman-installer/scenarios.d/last_scenario.yaml
----

Based upon the results of the above commands, the Satellite has 8 cores and 32 Gi of RAM. The recommended tuning profile is Medium, which does not match the default tuning profile that is currently applied.

Apply the Medium tuning profile
----
satellite-installer --tuning medium
----

Verify that the Profile has been applied
----
grep tuning /etc/foreman-installer/scenarios.d/last_scenario.yaml
----

== Automate the Cleanup of old content views

The number of Content View versions will continue to grow as Satellite continues to be utilized in an organization. In the past manual or scripted intevention was required to clean these obseleted Content Views up. Today, Satellite has automated tooling to perform these actions.

=== Scenario

The infrastructure team in your organization has been experimenting with different combinations of packages and content filters in the Satellite Server. This has created a large number of content view versions on the Satellite that are obselete.

View the content view versions on the Satellite and the Lifecycle Environments in which they are published:
----
hammer content-view list
----

Note that the <insert content view name here> Content View has 15 published versions.

Let's clean up these up:
----
hammer content-view purge --name <content-view-name> --organization <organization-name>
----

View that the content views versions have been purged:
----
hammer content-view version list --content-view <content-view-name>
----


By default this will keep the content-view versions that are promoted to Lifecycle Environments, and 3 unused versions.
After consulting with the infrastructure team, they have agreed that they only need 1 unused version.
Modyfy the previous command, by adding "--count 1" to the previous command to keep only 1 unused version
----
hammer content-view purge --name <content-view-name> --organization <organization-name> --count 1
----

Verify that the content-view versions have been purged:
View that the content views versions have been purged:
----
hammer content-view version list --content-view <content-view-name>
----

== Cleanup Orphaned Pulp Content

